#ifndef SHADOW_ALG_ENUM_H
#define SHADOW_ALG_ENUM_H

enum ShadowAlg
{
    NO_SHADOW = 0,
    NO_SHADOW_LIGHT,

    SHADOW_MAP_ORTHOGONAL,
    SHADOW_MAP_ORTHOGONAL_LIGHT,
    SHADOW_MAP_ORTHOGONAL_DEBUG,

    SHADOW_MAP_PERSPECTIVE,
    SHADOW_MAP_PERSPECTIVE_LIGHT,
    SHADOW_MAP_PERSPECTIVE_DEBUG,

    SHADOW_MAP_ORTHOGONAL_PCF,
    SHADOW_MAP_ORTHOGONAL_PCF_LIGHT,
    SHADOW_MAP_ORTHOGONAL_PCF_DEBUG,

    SHADOW_MAP_PERSPECTIVE_PCF,
    SHADOW_MAP_PERSPECTIVE_PCF_LIGHT,
    SHADOW_MAP_PERSPECTIVE_PCF_DEBUG
};

#endif // SHADOW_ALG_ENUM_H