#ifndef SHADOW_ALG_ENUM_H
#define SHADOW_ALG_ENUM_H

enum ShadowAlg
{
    NO_SHADOW = 0,
    NO_SHADOW_LIGHT,

    SHADOW_MAP_ORTHOGONAL,
    SHADOW_MAP_ORTHOGONAL_LIGHT,

    SHADOW_MAP_PERSPECTIVE,
    SHADOW_MAP_PERSPECTIVE_LIGHT,


};

#endif // SHADOW_ALG_ENUM_H