#ifndef TIME_UNITS_H
#define TIME_UNITS_H

#define MINUTE_PER_HOUR 60LL

#define SEC_PER_MINUTE 60LL
#define SEC_PER_HOUR   (SEC_PER_MINUTE * SEC_PER_HOUR)

#define MILLISEC_PER_SEC    1000LL
#define MILLISEC_PER_MINUTE (MILLISEC_PER_SEC * SEC_PER_MINUTE)
#define MILLISEC_PER_HOUR   (MILLISEC_PER_MINUTE * MINUTE_PER_HOUR)

#define MICROSEC_PER_MILLISEC 1000LL
#define MICROSEC_PER_SEC      (MICROSEC_PER_MILLISEC * MILLISEC_PER_SEC)
#define MICROSEC_PER_MINUTE   (MICROSEC_PER_SEC * SEC_PER_MINUTE)
#define MICROSEC_PER_HOUR     (MICROSEC_PER_MINUTE * MINUTE_PER_HOUR)

#define NANOSEC_PER_MICROSEC 1000LL
#define NANOSEC_PER_MILLISEC (NANOSEC_PER_MICROSEC * MICROSEC_PER_MILLISEC)
#define NANOSEC_PER_SEC      (NANOSEC_PER_MILLISEC * MILLISEC_PER_SEC)
#define NANOSEC_PER_MINUTE   (NANOSEC_PER_SEC * SEC_PER_MINUTE)
#define NANOSEC_PER_HOUR     (NANOSEC_PER_MINUTE * MINUTE_PER_HOUR)

#endif // TIME_UNITS_H